# Generated by Django 5.2.6 on 2025-10-01 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.responsavel'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
