# Generated by Django 5.2.6 on 2025-09-15 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='data_nasc',
            new_name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='email',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='historico_situacao',
        ),
        migrations.RemoveField(
            model_name='crianca',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='crianca',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.responsavel'),
        ),
    ]
