# Generated by Django 5.2.6 on 2025-10-06 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_consulta_responsavel_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='responsavel',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('profissional', 'Profissional'), ('responsavel', 'Responsável')], max_length=20)),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profissional')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.responsavel')),
            ],
        ),
    ]
